# Tamil Nadu Assembly Election Analysis (2021 vs 2026)

### <center><span style="color:blue; font-size:20px;"> Import Necessary Libraries </span></center>

In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns

pd.set_option('display.float_format', lambda x: '{:.2f}'.format(x))
np.set_printoptions(suppress=True)

### <center><span style="color:blue; font-size:20px;">Load the Dataset

#### Important

PLEASE DOWNLOAD THE 'Data' FILE AND RUN THIS

In [2]:
df_2021 = pd.read_csv("../Data/tn_2021_results.csv")
df_2026 = pd.read_csv("../Data/tn_2026_results.csv")
master = pd.read_csv("../Data/constituency_master.csv")

In [3]:
df_2021.sample(5)

,constituency,ac_number,candidate,party,votes,turnout,reserved,region
491,Saidapet,23,SNEGAPRIYA,MNM,13454,57.36,GEN,Chennai Metro
2931,Chidambaram,158,K.A. PANDIAN,AIADMK,91961,71.93,GEN,Central
3946,Ottapidaram,217,MURUGAN P,Naam Indiar Party,520,69.82,SC,South
2028,Coonoor,110,"Chandran, K.",IND,109,69.79,GEN,Kongu
152,Madavaram,9,RAMESH. G,IND,47,66.37,GEN,Chennai Metro

In [4]:
df_2026.sample(5)

,constituency,ac_number,candidate,party,votes,turnout,reserved,region
4138,Nanguneri,227,T. LINGADURAI,IND,178,NaN,GEN,South
2835,Thuraiyur,146,T. RAJAMANICKAM,Puthiya Tamilagam,236,NaN,SC,Delta
3335,Thirumayam,181,LAKSHMI SRINIVASAN,NTK,9102,NaN,GEN,Delta
3577,Thirumangalam,196,MUTHURAJA.M,IND,83,NaN,GEN,South
3371,Aranthangi,183,ABDUL JAFFAR. S,IND,322,NaN,GEN,Delta

In [5]:
master.sample(5)

     ac_number  constituency        district   region reserved
68          69     Vandavasi  Tiruvannamalai    North       SC
93          94      Namakkal        Namakkal  Central      GEN
111        112      Avanashi         Tirupur    Kongu       SC
79          80  Kallakurichi      Villupuram  Central       SC
35          36   Uthiramerur     Kanchipuram    North      GEN

### <center><span style="color:blue; font-size:20px;"> Data Preprocessing - Cleaning & EDA

In [6]:
print("2021 Shape :", df_2021.shape)
print("2026 Shape :", df_2026.shape)
print("Master Shape :", master.shape)

print("\n2021 Missing Values")
print(df_2021.isnull().sum())

print("\n2026 Missing Values")
print(df_2026.isnull().sum())

2021 Shape : (4232, 8)
2026 Shape : (4257, 8)
Master Shape : (234, 5)

2021 Missing Values
constituency    0
ac_number       0
candidate       0
party           0
votes           0
turnout         0
reserved        0
region          0
dtype: int64

2026 Missing Values
constituency       0
ac_number          0
candidate          0
party              0
votes              0
turnout         4257
reserved           0
region             0
dtype: int64

In [7]:
df_2021.duplicated().sum(), df_2026.duplicated().sum()

(0, 0)

#### To check if there are any discrepancies in party names

In [8]:
sorted(df_2021['party'].unique())

['AIADMK',
 'AIMIM',
 'AISMK',
 'AITC',
 'AMMK',
 'Aanaithinthiya Jananayaka Pathukappu Kazhagam',
 'Ahimsa Socialist Party',
 'Akhil Bharat Hindu Mahasabha',
 'Akhila India Jananayaka Makkal Katchi (Dr. Isaac)',
 'Akila India Vallalar Peravai',
 'All  India  Pattali  Munnetra Katchi',
 'All India Jananayaka Makkal Kazhagam',
 'All India MGR Makkal Munnetra Kazhagam',
 'All India Uzhavargal Uzhaippalargal Katchi',
 'All India Youth Development Party',
 'All Pensioner’s Party',
 'Ambedkar Political Party',
 'Ambedkarite Party of India',
 'Anaithindia Samudaya Munnetra Kazhagam',
 'Anaithu Makkal Arasiyal Katchi',
 'Anaithu Makkal Munnetra Kazhagam',
 'Anaithu Makkal Puratchi Katchi',
 'Anaithu Ulaga Tamilargal Munnetra Kalagam',
 'Anna Dravidar Kazhagam',
 'Anna MGR Dravida Makkal Kalgam',
 'Anna MGR Dravida Munnetra Kazhagam',
 'Anna Puratchi Thalaivar Amma Dravida Munnetra Kazhagam',
 'BJP',
 'BSP',
 'Bahujan Dravida Party',
 'Bhartiya Manavadhikaar Federal Party',
 'CPI',
 'CPI(M)',
 'CPI(ML)(L)',
 'DMDK',
 'DMK',
 'Desa Makkal Munnetrak Kazhgam',
 'Desiya Makkal Sakthi Katchi',
 'Desiya Sirupanmayinar Makkal Iyakkam',
 'Dhesiya Makkal Kazhagam',
 'Dravida Murpokku Makkal Katchi',
 'Ezhuchi Tamilargal Munnetra Kazhagam',
 'Ganasangam Party of India',
 'Hindustan Janta Party',
 'IJK',
 'INC',
 'IND',
 'IUML',
 'Ilantamilar Munnani Kazhagam',
 'Indhia Kudiarasu Katchi',
 'India Dravida Makkal Munnetra Katchi',
 'JD(S)',
 'Jebamani Janata',
 'Kamarajar Deseeya Congress',
 'Kongu  Desa  Marumalarchi  Makkal  Katchi',
 'LJP',
 'MAKKAL SAKTHI KATCHI',
 'MGR Makkal Katchi',
 'MNM',
 'Mahathma Makkal Munnetra Kazhakam',
 'Makkal Munnetra Peravai',
 'Makkal Nala Kazhagam',
 'Makkal Nalvaazhvuk Katchi',
 'Makkal Sananayaga Kudiyarasu Katchi,',
 'Makkal Thilagam Munnetra Kazhagam,',
 'Makkalatchi Katchi',
 'Manitha Urimaigal Kalaagam',
 'My India Party',
 'NCP',
 'NOTA',
 'NPP',
 'NTK',
 'Naadaalum Makkal Katchi',
 'Naam Indiar Party',
 'Nam India Naam Indiyar Katchi',
 'Namadhu Makkal Katchi',
 'Namathu Kongu Munnetra Kalagam',
 'National Democratic Party of South India',
 'New Generation People’s Party',
 'PMK',
 "People's Party of India(secular)",
 'Puthiya Tamilagam',
 'RJD',
 'RPI(A)',
 'RSPS',
 'Rashtriya Ulama Council',
 'Republican Party of India  (Sivaraj)',
 'SDPI',
 'SHS',
 'SP',
 'SUCI',
 'Samaniya Makkal Nala Katchi',
 'Samata Party',
 'South India Forward Bloc',
 'Tamil Nadu Ilangyar Katchi',
 'Tamil Telugu National Party',
 'Tamilaga Makkal Thannurimai Katchi',
 'Tamilnadu Mahatma Gandhi Makkal Katchi',
 'Tamilnadu Makkal Nalvazhvu Periyakkam',
 'Tamizhaga Murpokku Makkal Katchi',
 'Thamizhaga Munnetra Congress',
 'Tipu Sultan Party',
 'Ulaga Makkal Katchi',
 'United States of India Party',
 'Universal Brotherhood Movement',
 'VCK',
 'Valamaana  Tamizhagam   Katchi',
 'Veerath Thiyagi Viswanathadoss Thozhilalarkal Katchi',
 'Vidial Valarchi Perani']

In [9]:
sorted(df_2021['party'].unique())

['AIADMK',
 'AIMIM',
 'AISMK',
 'AITC',
 'AMMK',
 'Aanaithinthiya Jananayaka Pathukappu Kazhagam',
 'Ahimsa Socialist Party',
 'Akhil Bharat Hindu Mahasabha',
 'Akhila India Jananayaka Makkal Katchi (Dr. Isaac)',
 'Akila India Vallalar Peravai',
 'All  India  Pattali  Munnetra Katchi',
 'All India Jananayaka Makkal Kazhagam',
 'All India MGR Makkal Munnetra Kazhagam',
 'All India Uzhavargal Uzhaippalargal Katchi',
 'All India Youth Development Party',
 'All Pensioner’s Party',
 'Ambedkar Political Party',
 'Ambedkarite Party of India',
 'Anaithindia Samudaya Munnetra Kazhagam',
 'Anaithu Makkal Arasiyal Katchi',
 'Anaithu Makkal Munnetra Kazhagam',
 'Anaithu Makkal Puratchi Katchi',
 'Anaithu Ulaga Tamilargal Munnetra Kalagam',
 'Anna Dravidar Kazhagam',
 'Anna MGR Dravida Makkal Kalgam',
 'Anna MGR Dravida Munnetra Kazhagam',
 'Anna Puratchi Thalaivar Amma Dravida Munnetra Kazhagam',
 'BJP',
 'BSP',
 'Bahujan Dravida Party',
 'Bhartiya Manavadhikaar Federal Party',
 'CPI',
 'CPI(M)',
 'CPI(ML)(L)',
 'DMDK',
 'DMK',
 'Desa Makkal Munnetrak Kazhgam',
 'Desiya Makkal Sakthi Katchi',
 'Desiya Sirupanmayinar Makkal Iyakkam',
 'Dhesiya Makkal Kazhagam',
 'Dravida Murpokku Makkal Katchi',
 'Ezhuchi Tamilargal Munnetra Kazhagam',
 'Ganasangam Party of India',
 'Hindustan Janta Party',
 'IJK',
 'INC',
 'IND',
 'IUML',
 'Ilantamilar Munnani Kazhagam',
 'Indhia Kudiarasu Katchi',
 'India Dravida Makkal Munnetra Katchi',
 'JD(S)',
 'Jebamani Janata',
 'Kamarajar Deseeya Congress',
 'Kongu  Desa  Marumalarchi  Makkal  Katchi',
 'LJP',
 'MAKKAL SAKTHI KATCHI',
 'MGR Makkal Katchi',
 'MNM',
 'Mahathma Makkal Munnetra Kazhakam',
 'Makkal Munnetra Peravai',
 'Makkal Nala Kazhagam',
 'Makkal Nalvaazhvuk Katchi',
 'Makkal Sananayaga Kudiyarasu Katchi,',
 'Makkal Thilagam Munnetra Kazhagam,',
 'Makkalatchi Katchi',
 'Manitha Urimaigal Kalaagam',
 'My India Party',
 'NCP',
 'NOTA',
 'NPP',
 'NTK',
 'Naadaalum Makkal Katchi',
 'Naam Indiar Party',
 'Nam India Naam Indiyar Katchi',
 'Namadhu Makkal Katchi',
 'Namathu Kongu Munnetra Kalagam',
 'National Democratic Party of South India',
 'New Generation People’s Party',
 'PMK',
 "People's Party of India(secular)",
 'Puthiya Tamilagam',
 'RJD',
 'RPI(A)',
 'RSPS',
 'Rashtriya Ulama Council',
 'Republican Party of India  (Sivaraj)',
 'SDPI',
 'SHS',
 'SP',
 'SUCI',
 'Samaniya Makkal Nala Katchi',
 'Samata Party',
 'South India Forward Bloc',
 'Tamil Nadu Ilangyar Katchi',
 'Tamil Telugu National Party',
 'Tamilaga Makkal Thannurimai Katchi',
 'Tamilnadu Mahatma Gandhi Makkal Katchi',
 'Tamilnadu Makkal Nalvazhvu Periyakkam',
 'Tamizhaga Murpokku Makkal Katchi',
 'Thamizhaga Munnetra Congress',
 'Tipu Sultan Party',
 'Ulaga Makkal Katchi',
 'United States of India Party',
 'Universal Brotherhood Movement',
 'VCK',
 'Valamaana  Tamizhagam   Katchi',
 'Veerath Thiyagi Viswanathadoss Thozhilalarkal Katchi',
 'Vidial Valarchi Perani']

In [10]:
# There are 234 constituencies as per ECI

df_2021['constituency'].nunique()

233

In [11]:
df_2021[df_2021['constituency'] == "Tiruppattur"][['ac_number', 'constituency']]

      ac_number constituency
960          50  Tiruppattur
961          50  Tiruppattur
962          50  Tiruppattur
963          50  Tiruppattur
964          50  Tiruppattur
965          50  Tiruppattur
966          50  Tiruppattur
967          50  Tiruppattur
968          50  Tiruppattur
969          50  Tiruppattur
970          50  Tiruppattur
971          50  Tiruppattur
972          50  Tiruppattur
973          50  Tiruppattur
974          50  Tiruppattur
975          50  Tiruppattur
3313        185  Tiruppattur
3314        185  Tiruppattur
3315        185  Tiruppattur
3316        185  Tiruppattur
3317        185  Tiruppattur
3318        185  Tiruppattur
3319        185  Tiruppattur
3320        185  Tiruppattur
3321        185  Tiruppattur
3322        185  Tiruppattur
3323        185  Tiruppattur
3324        185  Tiruppattur
3325        185  Tiruppattur
3326        185  Tiruppattur
3327        185  Tiruppattur
3328        185  Tiruppattur
3329        185  Tiruppattur
3330        185  Tiruppattur
3331        185  Tiruppattur
3332        185  Tiruppattur
3333        185  Tiruppattur
3334        185  Tiruppattur
3335        185  Tiruppattur
3336        185  Tiruppattur
3337        185  Tiruppattur
3338        185  Tiruppattur
3339        185  Tiruppattur

Constituency 'Tirupattur' appears twice, under ac_number 185, and 50, hence we use ac_number as the primary key

In [12]:
df_2026['ac_number'].nunique()

234

In [13]:
df_2026[df_2026['constituency'] == "Tiruppattur"][['ac_number', 'constituency']]

      ac_number constituency
986          50  Tiruppattur
987          50  Tiruppattur
988          50  Tiruppattur
989          50  Tiruppattur
990          50  Tiruppattur
991          50  Tiruppattur
992          50  Tiruppattur
993          50  Tiruppattur
994          50  Tiruppattur
995          50  Tiruppattur
996          50  Tiruppattur
997          50  Tiruppattur
998          50  Tiruppattur
999          50  Tiruppattur
1000         50  Tiruppattur
1001         50  Tiruppattur
1002         50  Tiruppattur
1003         50  Tiruppattur
1004         50  Tiruppattur
1005         50  Tiruppattur
1006         50  Tiruppattur
1007         50  Tiruppattur
1008         50  Tiruppattur
1009         50  Tiruppattur
1010         50  Tiruppattur
3404        185  Tiruppattur
3405        185  Tiruppattur
3406        185  Tiruppattur
3407        185  Tiruppattur
3408        185  Tiruppattur
3409        185  Tiruppattur
3410        185  Tiruppattur
3411        185  Tiruppattur
3412        185  Tiruppattur
3413        185  Tiruppattur
3414        185  Tiruppattur
3415        185  Tiruppattur
3416        185  Tiruppattur
3417        185  Tiruppattur
3418        185  Tiruppattur
3419        185  Tiruppattur

#### Merge election results with constituency metadata

In [14]:
merged_2021 = pd.merge(
    df_2021,
    master,
    on='ac_number',
    how='left',
    suffixes=('', '_master')
)

In [15]:
merged_2021.head()

,constituency,ac_number,candidate,party,votes,turnout,reserved,region,constituency_master,district,region_master,reserved_master
0,Gummidipundi,1,GOVINDARAJAN T.J,DMK,126452,78.08,GEN,Chennai Metro,Gummidipundi,Tiruvallur,Chennai Metro,GEN
1,Gummidipundi,1,PRAKASH M,PMK,75514,78.08,GEN,Chennai Metro,Gummidipundi,Tiruvallur,Chennai Metro,GEN
2,Gummidipundi,1,USHA,NTK,11701,78.08,GEN,Chennai Metro,Gummidipundi,Tiruvallur,Chennai Metro,GEN
3,Gummidipundi,1,DILLIY K.M,DMDK,2576,78.08,GEN,Chennai Metro,Gummidipundi,Tiruvallur,Chennai Metro,GEN
4,Gummidipundi,1,None Of The Above,NOTA,1783,78.08,GEN,Chennai Metro,Gummidipundi,Tiruvallur,Chennai Metro,GEN

In [16]:
merged_2026 = pd.merge(
    df_2026,
    master,
    on='ac_number',
    how='left',
    suffixes=('', '_master')
)

In [17]:
merged_2026.head()

,constituency,ac_number,candidate,party,votes,turnout,reserved,region,constituency_master,district,region_master,reserved_master
0,Gummidipoondi,1,S.VIJAYAKUMAR,TVK,94320,NaN,GEN,Chennai Metro,Gummidipundi,Tiruvallur,Chennai Metro,GEN
1,Gummidipoondi,1,SUDHAKAR.V,AIADMK,66375,NaN,GEN,Chennai Metro,Gummidipundi,Tiruvallur,Chennai Metro,GEN
2,Gummidipoondi,1,T.J.GOVINDARAJAN,DMK,62492,NaN,GEN,Chennai Metro,Gummidipundi,Tiruvallur,Chennai Metro,GEN
3,Gummidipoondi,1,"R.SRIDAR. B.L.,",NTK,4756,NaN,GEN,Chennai Metro,Gummidipundi,Tiruvallur,Chennai Metro,GEN
4,Gummidipoondi,1,NOTA,NOTA,937,NaN,GEN,Chennai Metro,Gummidipundi,Tiruvallur,Chennai Metro,GEN

In [18]:
merged_2021.shape, merged_2026.shape

((4232, 12), (4257, 12))

#### Keeping only the necessary columns

In [19]:
merged_2021 = merged_2021[[
    'ac_number',
    'constituency',
    'candidate',
    'party',
    'votes',
    'region',
    'district'
]]

merged_2026 = merged_2026[[
    'ac_number',
    'constituency',
    'candidate',
    'party',
    'votes',
    'region',
    'district'
]]

In [20]:
df_2021['region'].unique()

array(['Chennai Metro', 'North', 'Central', 'Kongu', 'South', 'Delta'],
      dtype=object)

In [21]:
df_2026['region'].unique()

array(['Chennai Metro', 'North', 'Central', 'Kongu', 'South', 'Delta'],
      dtype=object)

In [22]:
merged_2021.head()

,ac_number,constituency,candidate,party,votes,region,district
0,1,Gummidipundi,GOVINDARAJAN T.J,DMK,126452,Chennai Metro,Tiruvallur
1,1,Gummidipundi,PRAKASH M,PMK,75514,Chennai Metro,Tiruvallur
2,1,Gummidipundi,USHA,NTK,11701,Chennai Metro,Tiruvallur
3,1,Gummidipundi,DILLIY K.M,DMDK,2576,Chennai Metro,Tiruvallur
4,1,Gummidipundi,None Of The Above,NOTA,1783,Chennai Metro,Tiruvallur

In [23]:
merged_2021.shape, merged_2026.shape

((4232, 7), (4257, 7))

### <center><span style="color:blue; font-size:20px;"> Feature Engineering & Analytical Table Creation

### WINNER EXTRACTION

#### Identify winning candidate and party for each constituency

In [24]:
winner_2021 = merged_2021.loc[
    merged_2021.groupby('ac_number')['votes'].idxmax()
].copy()

In [25]:
winner_2021 = winner_2021.rename(columns={
    'party': 'winning_party_2021',
    'candidate': 'winning_candidate_2021',
    'votes': 'total_votes_2021'
})

In [26]:
# Keep only required columns
winner_2021 = winner_2021[[
    'ac_number',
    'constituency',
    'region',
    'district',
    'winning_party_2021',
    'winning_candidate_2021',
    'total_votes_2021'
]]

In [27]:
winner_2026 = merged_2026.loc[
    merged_2026.groupby('ac_number')['votes'].idxmax()
].copy()

In [28]:
# Rename columns
winner_2026 = winner_2026.rename(columns={
    'party': 'winning_party_2026',
    'candidate': 'winning_candidate_2026',
    'votes': 'total_votes_2026'
})

In [29]:
# Keep only required columns
winner_2026 = winner_2026[[
    'ac_number',
    'constituency',
    'region',
    'district',
    'winning_party_2026',
    'winning_candidate_2026',
    'total_votes_2026'
]]

In [30]:
flip_analysis = pd.merge(
    winner_2021,
    winner_2026,
    on='ac_number',
    how='inner'
)
flip_analysis.head()

,ac_number,constituency_x,region_x,district_x,winning_party_2021,winning_candidate_2021,total_votes_2021,constituency_y,region_y,district_y,winning_party_2026,winning_candidate_2026,total_votes_2026
0,1,Gummidipundi,Chennai Metro,Tiruvallur,DMK,GOVINDARAJAN T.J,126452,Gummidipoondi,Chennai Metro,Tiruvallur,TVK,S.VIJAYAKUMAR,94320
1,2,Ponneri,Chennai Metro,Tiruvallur,INC,DURAI. CHANDRASEKAR,94528,Ponneri,Chennai Metro,Tiruvallur,TVK,DR.RAVI.M.S,110439
2,3,Tiruttani,Chennai Metro,Tiruvallur,DMK,S.Chandran,120314,Tiruttani,Chennai Metro,Tiruvallur,AIADMK,G.HARI,89169
3,4,Thiruvallur,Chennai Metro,Tiruvallur,DMK,"RAAJENDRAN, V.G.",107709,Thiruvallur,Chennai Metro,Tiruvallur,TVK,DR. T. ARUNKUMAR,92190
4,5,Poonamallee,Chennai Metro,Tiruvallur,DMK,Krishnaswamy A,149578,Poonamallee,Chennai Metro,Tiruvallur,TVK,PRAKASAM.R,161309

### FLIP ANALYSIS

#### Compare 2021 and 2026 winners to identify flipped constituencies

In [31]:
flip_analysis['Flipped?'] = np.where(
    flip_analysis['winning_party_2021']
    !=
    flip_analysis['winning_party_2026'],
    'Yes',
    'No'
)

In [32]:
flip_analysis = flip_analysis[[
    'ac_number',
    'constituency_x',
    'region_x',
    'district_x',
    'winning_party_2021',
    'winning_candidate_2021',
    'winning_party_2026',
    'winning_candidate_2026',
    'total_votes_2021',
    'total_votes_2026',
    'Flipped?'
]]

In [33]:
# Rename columns
flip_analysis = flip_analysis.rename(columns={
    'region_x': 'region',
    'district_x': 'district',
    'constituency_x': 'constituency'
})

In [34]:
flip_analysis.head()

,ac_number,constituency,region,district,winning_party_2021,winning_candidate_2021,winning_party_2026,winning_candidate_2026,total_votes_2021,total_votes_2026,Flipped?
0,1,Gummidipundi,Chennai Metro,Tiruvallur,DMK,GOVINDARAJAN T.J,TVK,S.VIJAYAKUMAR,126452,94320,Yes
1,2,Ponneri,Chennai Metro,Tiruvallur,INC,DURAI. CHANDRASEKAR,TVK,DR.RAVI.M.S,94528,110439,Yes
2,3,Tiruttani,Chennai Metro,Tiruvallur,DMK,S.Chandran,AIADMK,G.HARI,120314,89169,Yes
3,4,Thiruvallur,Chennai Metro,Tiruvallur,DMK,"RAAJENDRAN, V.G.",TVK,DR. T. ARUNKUMAR,107709,92190,Yes
4,5,Poonamallee,Chennai Metro,Tiruvallur,DMK,Krishnaswamy A,TVK,PRAKASAM.R,149578,161309,Yes

In [35]:
print("\nShape of Final Table:")
print(flip_analysis.shape)

Shape of Final Table:
(234, 11)

### ALLIANCE MAPPING

#### Map parties into broader alliance classifications for comparative analysis

In [36]:
sorted(flip_analysis['winning_party_2021'].unique())

['AIADMK', 'BJP', 'CPI', 'CPI(M)', 'DMK', 'INC', 'PMK', 'VCK']

In [37]:
sorted(flip_analysis['winning_party_2026'].unique())

['AIADMK',
 'AMMK',
 'BJP',
 'CPI',
 'CPI(M)',
 'DMDK',
 'DMK',
 'INC',
 'IUML',
 'PMK',
 'TVK',
 'VCK']

In [38]:
# =========================================================
# CREATE ALLIANCE COLUMNS
# =========================================================

# =========================================================
# 2021 ALLIANCE MAPPING
# =========================================================

alliance_2021_map = {

    # DMK Alliance
    'DMK': 'DMK+',
    'CPI': 'DMK+',
    'CPI(M)': 'DMK+',
    'INC': 'DMK+',
    'VCK': 'DMK+',

    # AIADMK Alliance
    'AIADMK': 'AIADMK+',
    'BJP': 'AIADMK+',
    'PMK': 'AIADMK+'
}

# =========================================================
# CREATE 2021 ALLIANCE COLUMN
# =========================================================

flip_analysis['winning_party_alliance_2021'] = (
    flip_analysis['winning_party_2021']
    .map(alliance_2021_map)
)

# =========================================================
# 2026 ALLIANCE MAPPING
# =========================================================

alliance_2026_map = {

    # DMK Alliance
    'DMK': 'DMK+',
    'CPI': 'DMK+',
    'CPI(M)': 'DMK+',
    'DMDK': 'DMK+',
    'INC': 'DMK+',
    'IUML': 'DMK+',
    'VCK': 'DMK+',

    # AIADMK Alliance
    'AIADMK': 'AIADMK+',
    'AMMK': 'AIADMK+',
    'BJP': 'AIADMK+',
    'PMK': 'AIADMK+',

    # TVK
    'TVK': 'TVK'
}

# =========================================================
# CREATE 2026 ALLIANCE COLUMN
# =========================================================

flip_analysis['winning_party_alliance_2026'] = (
    flip_analysis['winning_party_2026']
    .map(alliance_2026_map)
)


# =========================================================
# CHECK OUTPUT
# =========================================================

flip_analysis.head()

,ac_number,constituency,region,district,winning_party_2021,winning_candidate_2021,winning_party_2026,winning_candidate_2026,total_votes_2021,total_votes_2026,Flipped?,winning_party_alliance_2021,winning_party_alliance_2026
0,1,Gummidipundi,Chennai Metro,Tiruvallur,DMK,GOVINDARAJAN T.J,TVK,S.VIJAYAKUMAR,126452,94320,Yes,DMK+,TVK
1,2,Ponneri,Chennai Metro,Tiruvallur,INC,DURAI. CHANDRASEKAR,TVK,DR.RAVI.M.S,94528,110439,Yes,DMK+,TVK
2,3,Tiruttani,Chennai Metro,Tiruvallur,DMK,S.Chandran,AIADMK,G.HARI,120314,89169,Yes,DMK+,AIADMK+
3,4,Thiruvallur,Chennai Metro,Tiruvallur,DMK,"RAAJENDRAN, V.G.",TVK,DR. T. ARUNKUMAR,107709,92190,Yes,DMK+,TVK
4,5,Poonamallee,Chennai Metro,Tiruvallur,DMK,Krishnaswamy A,TVK,PRAKASAM.R,149578,161309,Yes,DMK+,TVK

### REGIONAL ANALYSIS

#### Aggregate seat counts region-wise for alliance-level comparison

In [39]:
# =========================================================
# STEP 1 — CREATE ALLIANCE COLUMN FOR 2021
# =========================================================

alliance_2021_map = {

    # DMK Alliance
    'DMK': 'DMK+',
    'CPI': 'DMK+',
    'CPI(M)': 'DMK+',
    'INC': 'DMK+',
    'VCK': 'DMK+',

    # AIADMK Alliance
    'AIADMK': 'AIADMK+',
    'BJP': 'AIADMK+',
    'PMK': 'AIADMK+',

    # NTK
    'NTK': 'NTK'
}

# Create alliance column
winner_2021['alliance'] = (
    winner_2021['winning_party_2021']
    .map(alliance_2021_map)
    .fillna('Others')
)

# =========================================================
# STEP 2 — CREATE ALLIANCE COLUMN FOR 2026
# =========================================================

alliance_2026_map = {

    # DMK Alliance
    'DMK': 'DMK+',
    'CPI': 'DMK+',
    'CPI(M)': 'DMK+',
    'DMDK': 'DMK+',
    'INC': 'DMK+',
    'IUML': 'DMK+',
    'VCK': 'DMK+',

    # AIADMK Alliance
    'AIADMK': 'AIADMK+',
    'AMMK': 'AIADMK+',
    'BJP': 'AIADMK+',
    'PMK': 'AIADMK+',

    # TVK
    'TVK': 'TVK',

    # NTK
    'NTK': 'NTK'
}

# Create alliance column
winner_2026['alliance'] = (
    winner_2026['winning_party_2026']
    .map(alliance_2026_map)
    .fillna('Others')
)

# =========================================================
# STEP 3 — REGION-WISE SEAT COUNT (2021)
# =========================================================

region_seats_2021 = (
    winner_2021
    .groupby(['region', 'alliance'])
    .size()
    .reset_index(name='no_seats_2021')
)

# =========================================================
# STEP 4 — REGION-WISE SEAT COUNT (2026)
# =========================================================

region_seats_2026 = (
    winner_2026
    .groupby(['region', 'alliance'])
    .size()
    .reset_index(name='no_seats_2026')
)

# =========================================================
# STEP 5 — MERGE BOTH YEARS
# =========================================================

region_seat_comparison = pd.merge(
    region_seats_2021,
    region_seats_2026,
    on=['region', 'alliance'],
    how='outer'
)

# =========================================================
# STEP 6 — FILL MISSING VALUES WITH 0
# =========================================================

region_seat_comparison['no_seats_2021'] = (
    region_seat_comparison['no_seats_2021']
    .fillna(0)
    .astype(int)
)

region_seat_comparison['no_seats_2026'] = (
    region_seat_comparison['no_seats_2026']
    .fillna(0)
    .astype(int)
)

# =========================================================
# STEP 7 — CREATE NET CHANGE COLUMN
# =========================================================

region_seat_comparison['net_change'] = (
    region_seat_comparison['no_seats_2026']
    -
    region_seat_comparison['no_seats_2021']
)

# =========================================================
# STEP 8 — SORT TABLE
# =========================================================

region_seat_comparison = region_seat_comparison.sort_values(
    ['region', 'alliance']
)
region_seat_comparison

           region alliance  no_seats_2021  no_seats_2026  net_change
0         Central  AIADMK+             18             18           0
1         Central     DMK+             23             11         -12
2         Central      TVK              0             12          12
3   Chennai Metro  AIADMK+              0              1           1
4   Chennai Metro     DMK+             32              2         -30
5   Chennai Metro      TVK              0             29          29
6           Delta  AIADMK+              4              5           1
7           Delta     DMK+             29             18         -11
8           Delta      TVK              0             10          10
9           Kongu  AIADMK+             21              8         -13
10          Kongu     DMK+             12              9          -3
11          Kongu      TVK              0             16          16
12          North  AIADMK+             14             16           2
13          North     DMK+             23              6         -17
14          North      TVK              0             15          15
15          South  AIADMK+             18              5         -13
16          South     DMK+             40             27         -13
17          South      TVK              0             26          26

### SANKEY PREPARATION

### Prepare alliance transition flows for Sankey visualization

In [40]:
# =========================================================
# CREATE SANKEY DATA
# =========================================================

# Count constituency flows
sankey_data = (
    flip_analysis
    .groupby([
        'winning_party_alliance_2021',
        'winning_party_alliance_2026'
    ])
    .size()
    .reset_index(name='Count')
)

# =========================================================
# RENAME COLUMNS
# =========================================================

sankey_data.columns = [
    'source',
    'target',
    'count'
]

# =========================================================
# CHECK OUTPUT
# =========================================================


sankey_data

    source   target  count
0  AIADMK+  AIADMK+     25
1  AIADMK+     DMK+     20
2  AIADMK+      TVK     30
3     DMK+  AIADMK+     28
4     DMK+     DMK+     53
5     DMK+      TVK     78

In [41]:
25+20+30+28+53+78

234

### Victory Margin Calculation

#### Calculate constituency-level victory margins using winner and runner-up vote difference.

In [42]:
# =========================================================
# FUNCTION TO CALCULATE MARGIN
# =========================================================

def calculate_margin(df, year):

    # -----------------------------------------------------
    # SORT CANDIDATES BY VOTES (HIGH TO LOW)
    # -----------------------------------------------------

    sorted_df = df.sort_values(
        ['ac_number', 'votes'],
        ascending=[True, False]
    )

    # -----------------------------------------------------
    # GET TOP 2 CANDIDATES IN EACH CONSTITUENCY
    # -----------------------------------------------------

    top2 = (
        sorted_df
        .groupby('ac_number')
        .head(2)
    ).copy()

    # -----------------------------------------------------
    # RANK CANDIDATES
    # -----------------------------------------------------

    top2['rank'] = (
        top2
        .groupby('ac_number')['votes']
        .rank(method='first', ascending=False)
    )

    # -----------------------------------------------------
    # SPLIT WINNER & RUNNER-UP
    # -----------------------------------------------------

    winner = top2[top2['rank'] == 1].copy()
    runner = top2[top2['rank'] == 2].copy()

    # -----------------------------------------------------
    # RENAME COLUMNS
    # -----------------------------------------------------

    winner = winner.rename(columns={
        'votes': f'winner_votes_{year}'
    })

    runner = runner.rename(columns={
        'votes': f'runner_votes_{year}'
    })

    # -----------------------------------------------------
    # MERGE WINNER + RUNNER-UP
    # -----------------------------------------------------

    margin_df = pd.merge(
        winner[
            ['ac_number', 'region', f'winner_votes_{year}']
        ],
        runner[
            ['ac_number', f'runner_votes_{year}']
        ],
        on='ac_number'
    )

    # -----------------------------------------------------
    # CALCULATE MARGIN
    # -----------------------------------------------------

    margin_df[f'margin_{year}'] = (
        margin_df[f'winner_votes_{year}']
        -
        margin_df[f'runner_votes_{year}']
    )

    return margin_df


# =========================================================
# CALCULATE FOR BOTH YEARS
# =========================================================

margin_2021 = calculate_margin(merged_2021, 2021)

margin_2026 = calculate_margin(merged_2026, 2026)

# =========================================================
# REGION-WISE AVERAGE MARGIN
# =========================================================

region_margin_2021 = (
    margin_2021
    .groupby('region')['margin_2021']
    .mean()
    .reset_index()
)

region_margin_2021 = region_margin_2021.rename(columns={
    'margin_2021': 'average_margin_2021'
})

region_margin_2026 = (
    margin_2026
    .groupby('region')['margin_2026']
    .mean()
    .reset_index()
)

region_margin_2026 = region_margin_2026.rename(columns={
    'margin_2026': 'average_margin_2026'
})

# =========================================================
# MERGE REGION TABLES
# =========================================================

region_margin_comparison = pd.merge(
    region_margin_2021,
    region_margin_2026,
    on='region'
)

# =========================================================
# CREATE NET CHANGE
# =========================================================

region_margin_comparison['net_change'] = (
    region_margin_comparison['average_margin_2026']
    -
    region_margin_comparison['average_margin_2021']
)

region_margin_comparison['average_margin_2021'] = (
    region_margin_comparison['average_margin_2021']
    .round()
    .astype(int)
)

region_margin_comparison['average_margin_2026'] = (
    region_margin_comparison['average_margin_2026']
    .round()
    .astype(int)
)

region_margin_comparison['net_change'] = (
    region_margin_comparison['net_change']
    .round()
    .astype(int)
)


# =========================================================
# OVERALL STATE AVERAGE MARGIN
# =========================================================

overall_avg_margin_2021 = (
    margin_2021['margin_2021']
    .mean()
)

overall_avg_margin_2026 = (
    margin_2026['margin_2026']
    .mean()
)


overall_avg_margin_2021 = int(round(overall_avg_margin_2021))
overall_avg_margin_2026 = int(round(overall_avg_margin_2026))


overall_margin_table = pd.DataFrame({
    'Year': [2021, 2026],
    'overall_average_margin': [
        overall_avg_margin_2021,
        overall_avg_margin_2026
    ]
})

# =========================================================
# CHECK OUTPUTS
# =========================================================

print("\nREGION-WISE AVERAGE MARGIN")
print(region_margin_comparison)

print("\nOVERALL AVERAGE MARGIN")
print(overall_margin_table)

REGION-WISE AVERAGE MARGIN
          region  average_margin_2021  average_margin_2026  net_change
0        Central                18793                14512       -4280
1  Chennai Metro                36461                37560        1098
2          Delta                26007                13187      -12819
3          Kongu                15178                14054       -1123
4          North                17880                14811       -3069
5          South                24031                11787      -12244

OVERALL AVERAGE MARGIN
   Year  overall_average_margin
0  2021                   22871
1  2026                   16784

### Winner Vote Share Calculation

 This function calculates:
 1. Total valid votes in each constituency
 2. Winning candidate in each constituency
 3. Winner vote share percentage
 4. Final constituency-level vote share table

In [43]:
# =========================================================
# FUNCTION TO CALCULATE WINNER VOTE SHARE
# =========================================================

def winner_vote_share(df, year):

    # -----------------------------------------------------
    # TOTAL VALID VOTES IN EACH CONSTITUENCY
    # -----------------------------------------------------

    total_votes = (
        df
        .groupby('ac_number')['votes']
        .sum()
        .reset_index(name='total_valid_votes')
    )

    # -----------------------------------------------------
    # WINNING CANDIDATE
    # -----------------------------------------------------

    winners = df.loc[
        df.groupby('ac_number')['votes'].idxmax()
    ].copy()

    # -----------------------------------------------------
    # RENAME WINNER VOTES
    # -----------------------------------------------------

    winners = winners.rename(columns={
        'votes': 'winner_votes'
    })

    # -----------------------------------------------------
    # MERGE
    # -----------------------------------------------------

    vote_share = pd.merge(
        winners[
            [
                'ac_number',
                'constituency',
                'region',
                'party',
                'candidate',
                'winner_votes'
            ]
        ],
        total_votes,
        on='ac_number'
    )

    # -----------------------------------------------------
    # CALCULATE VOTE SHARE %
    # -----------------------------------------------------

    vote_share[f'vote_share_{year}'] = (
        vote_share['winner_votes']
        /
        vote_share['total_valid_votes']
    ) * 100

    # -----------------------------------------------------
    # ROUND
    # -----------------------------------------------------

    vote_share[f'vote_share_{year}'] = (
        vote_share[f'vote_share_{year}']
        .round(2)
    )

    return vote_share


# =========================================================
# CREATE DATASETS
# =========================================================

vote_share_2021 = winner_vote_share(merged_2021, 2021)

vote_share_2026 = winner_vote_share(merged_2026, 2026)

# =========================================================
# 2021 COUNTS
# =========================================================

gt_50_2021 = (
    vote_share_2021[
        vote_share_2021['vote_share_2021'] > 50
    ]
    .shape[0]
)

between_35_50_2021 = (
    vote_share_2021[
        (vote_share_2021['vote_share_2021'] >= 35)
        &
        (vote_share_2021['vote_share_2021'] <= 50)
    ]
    .shape[0]
)

lt_35_2021 = (
    vote_share_2021[
        vote_share_2021['vote_share_2021'] < 35
    ]
    .shape[0]
)

# =========================================================
# 2026 COUNTS
# =========================================================

gt_50_2026 = (
    vote_share_2026[
        vote_share_2026['vote_share_2026'] > 50
    ]
    .shape[0]
)

between_35_50_2026 = (
    vote_share_2026[
        (vote_share_2026['vote_share_2026'] >= 35)
        &
        (vote_share_2026['vote_share_2026'] <= 50)
    ]
    .shape[0]
)

lt_35_2026 = (
    vote_share_2026[
        vote_share_2026['vote_share_2026'] < 35
    ]
    .shape[0]
)

# =========================================================
# CREATE SUMMARY TABLE
# =========================================================

vote_share_summary = pd.DataFrame({

    'Year': [2021, 2026],

    '>50%_vote_share': [
        gt_50_2021,
        gt_50_2026
    ],

    '35%-50%_vote_share': [
        between_35_50_2021,
        between_35_50_2026
    ],

    '<35%_vote_share': [
        lt_35_2021,
        lt_35_2026
    ]
})

# =========================================================
# CHECK OUTPUT
# =========================================================

print(vote_share_summary)

   Year  >50%_vote_share  35%-50%_vote_share  <35%_vote_share
0  2021               70                 162                2
1  2026               13                 157               64

In [44]:
70+162+2, 13+157+64

(234, 234)

In [45]:
vote_share_2021

,ac_number,constituency,region,party,candidate,winner_votes,total_valid_votes,vote_share_2021
0,1,Gummidipundi,Chennai Metro,DMK,GOVINDARAJAN T.J,126452,222069,56.94
1,2,Ponneri,Chennai Metro,INC,DURAI. CHANDRASEKAR,94528,210354,44.94
2,3,Tiruttani,Chennai Metro,DMK,S.Chandran,120314,232624,51.72
3,4,Thiruvallur,Chennai Metro,DMK,"RAAJENDRAN, V.G.",107709,214243,50.27
4,5,Poonamallee,Chennai Metro,DMK,Krishnaswamy A,149578,263736,56.72
...,...,...,...,...,...,...,...,...
229,230,Nagercoil,South,BJP,Gandhi M.R.,88804,184185,48.21
230,231,Colachel,South,INC,Prince J.G.,90681,182969,49.56
231,232,Padmanabhapuram,South,DMK,"Mano Thangaraj, T.",87744,170156,51.57
232,233,Vilavancode,South,INC,VIJAYADHARANI S,87473,167836,52.12
233,234,Killiyoor,South,INC,RAJESH KUMAR S,101541,169918,59.76

In [46]:
vote_share_2026

,ac_number,constituency,region,party,candidate,winner_votes,total_valid_votes,vote_share_2026
0,1,Gummidipoondi,Chennai Metro,TVK,S.VIJAYAKUMAR,94320,232522,40.56
1,2,Ponneri,Chennai Metro,TVK,DR.RAVI.M.S,110439,226819,48.69
2,3,Tiruttani,Chennai Metro,AIADMK,G.HARI,89169,238798,37.34
3,4,Thiruvallur,Chennai Metro,TVK,DR. T. ARUNKUMAR,92190,226428,40.71
4,5,Poonamallee,Chennai Metro,TVK,PRAKASAM.R,161309,308894,52.22
...,...,...,...,...,...,...,...,...
229,230,Nagercoil,South,DMK,AUSTIN,69880,196280,35.60
230,231,Colachal,South,INC,THARAHAI CUTHBERT,66207,199013,33.27
231,232,Padmanabhapuram,South,CPI(M),CHELLASWAMY. R,68938,180555,38.18
232,233,Vilavancode,South,INC,PRAVEEN T.T,70755,174927,40.45
233,234,Killiyoor,South,INC,RAJESH KUMAR. S,66434,177534,37.42

 ### <center><span style="color:blue; font-size:20px;"> Exports

### Export tables for Power BI integration

In [47]:
# =========================================================
# EXPORT
# =========================================================

vote_share_summary.to_csv(
    "winner_vote_share_summary.csv",
    index=False
)

vote_share_2021.to_csv(
    "vote_share_2021.csv",
    index=False
)

vote_share_2026.to_csv(
    "vote_share_2026.csv",
    index=False
)

region_margin_comparison.to_csv(
    "region_margin_comparison.csv",
    index=False
)


overall_margin_table.to_csv(
    "overall_margin_table.csv",
    index=False
)


sankey_data.to_csv(
    "sankey_data.csv",
    index=False
)

region_seat_comparison.to_csv(
    "region_seat_comparison.csv",
    index=False
)

flip_analysis.to_csv(
    "flip_analysis.csv",
    index=False
)